# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-rds

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128

  # you can overwrite defaults here
  stage: dev
  region: ap-southeast-1

plugins:
  # - serverless-webpack # serverless webpack plugin
  - serverless-plugin-typescript
  - serverless-offline

# Lambda Functions
functions:
  - ${file(src/config/functions/OrderFunctions.yml)}
  - ${file(src/config/functions/EmployeeFunctions.yml)}
  - ${file(src/config/functions/ProductFunctions.yml)}
  - ${file(src/config/functions/CustomerFunctions.yml)}

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js
