getCustomers:
  handler: src/handlers/customer/getCustomers.handler
  events:
    - http:
        path: /customer
        method: GET
getCustomerOrders:
  handler: src/handlers/customer/customerOrders.handler
  events:
    - http:
        path: /customerOrders/{id}
        method: GET
getCustomerDetails:
  handler: src/handlers/customer/getCustomerDetails.handler
  events:
    - http:
        path: /customer/{id}
        method: GET
getDistinctCountry:
  handler: src/handlers/customer/getDistinctCountry.handler
  events:
    - http:
        path: /customer/country
        method: GET
